### ISSUE TITLE
`npm install` failing

### ISSUE THREAD

**Issue by tiffany352** [mozilla/twemoji-colr#52]
It seems like one of the prebuilt dependencies has been taken down, and I can't get this to compile locally. Am I doing something wrong?

```
> canvas-prebuilt@1.6.11 install /home/tiffany/git/twemoji-colr/node_modules/canvas-prebuilt
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/tiffany/git/twemoji-colr/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:215:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/tiffany/git/twemoji-colr/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:210:5)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:456:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:210:5)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:308:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:289:11)
node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
node-pre-gyp ERR! command "/usr/bin/node" "/home/tiffany/git/twemoji-colr/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /home/tiffany/git/twemoji-colr/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-linux-x64.tar.gz
```

**Comment by timdream** [comment]
> 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-linux-x64.tar.gz

You would need to investigate the dependency tree and figure out what package is dependent on `node-canvas`, and make sure they are using something that works with Node v12.13 on Linux.

Filing an issue on https://github.com/node-gfx/node-canvas-prebuilt may help.

**Comment by tiffany352** [comment]
I got it to build by downgrading from Node 12 to Node 11 and then upgrading the `resemblejs` dependency from 2.x to 3.2.0.
